### ISSUE TITLE
Did you have it for v1.0.7

### ISSUE THREAD

**Issue by s3vdev** [emanueleg/ttn-decoders#1]
Wee need this for the Firmware 1.0.7. This isn't [working](https://github.com/LoRaWAN-Product-Decoder/MOKOSMART-LoRaWAN-Product-Decoder/blob/main/LW001-BG%20PRO/LW001-BG%20PRO%20on%20chirpstack.js).

**Comment by emanueleg** [comment]
Sorry, can't help you. I do not work for Moko and I do not know what has changed in the firmware.
